### ISSUE TITLE
Not possible to upload dump to S3

### ISSUE THREAD

**Issue by bjora857** [larkinwhitaker/laravel-db-backup#1]
When running:
php artisan db:backup --upload-s3 my-bucket

I get the following error message "  [BadMethodCallException]
  Unknown method: get.
"

Commands/BackupCommand#123
It works fine if I change
`$s3 = AWS::get('s3');`
to
`$s3 = AWS::createClient('s3');`

**Comment by Audesi** [comment]
I'm getting this same issue. The above 'createClient' change is working for me.

**Comment by simplenotezy** [comment]
Fixed it in my fork: https://github.com/larkinwhitaker/laravel-db-backup/pull/4

**Comment by paulycloud** [comment]
Hi. This issue is still present in the package as of 7/22. Please update
#1 
   protected function uploadS3()
    {
        $bucket = $this->option('upload-s3');
        $s3 = AWS::get('s3');
        $s3->putObject([
            'Bucket'     => $bucket,
            'Key'        => $this->getS3DumpsPath() . '/' . $this->fileName,
            'SourceFile' => $this->filePath,
        ]);
    }
